package com.example.data.remote

object SupabaseConfig {
    // Default Supabase Project details for Find My CNI Cameroon
    var supabaseUrl: String = "https://findmycni-cm.supabase.co"
    var supabaseAnonKey: String = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpbmRteWNuaS1jbSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzE2MzE2ODAwLCJleHAiOjIwMzE4OTI4MDB9.EXAMPLE_SUPABASE_ANON_KEY"
    const val TABLE_NAME = "cni_declarations"

    val restEndpoint: String
        get() {
            val cleanUrl = supabaseUrl.trimEnd('/')
            return "$cleanUrl/rest/v1/$TABLE_NAME"
        }

    // SQL DDL schema for user reference when setting up Supabase
    const val SQL_SCHEMA_INSTRUCTIONS = """
    -- Table SQL pour Supabase Cloud:
    CREATE TABLE IF NOT EXISTS public.cni_declarations (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        entry_type text NOT NULL,
        full_name text NOT NULL,
        dob text,
        last_4_digits text,
        location text,
        declaration_doc_uri text,
        selfie_uri text,
        photo_uri text,
        description text,
        contact_phone text,
        status text DEFAULT 'EN_ATTENTE_VALIDATION',
        is_verified_by_authority boolean DEFAULT false,
        user_email text,
        created_at_formatted text,
        timestamp bigint
    );

    -- Politique de sécurité RLS (Row Level Security):
    ALTER TABLE public.cni_declarations ENABLE ROW LEVEL SECURITY;
    CREATE POLICY "Allow public read and insert" ON public.cni_declarations FOR ALL USING (true);
    """
}
