name: find_my_cni
description: "Find My CNI"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # LES 3 PACKAGES QUI CASSAIENT
  app_links: ^6.4.1
  url_launcher: ^6.3.0
  permission_handler: ^11.3.1
  
  # METS TES AUTRES PACKAGES ICI S'IL Y EN A
  # provider: ^6.1.2
  # http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  # Si tu as des assets
  # assets:
  #   - assets/
