name: find_my_cni
description: "Find My CNI - Application Flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # PACKAGES MIS A JOUR POUR FLUTTER 3.24.0
  app_links: ^3.5.2
  url_launcher: ^6.3.0
  permission_handler: ^11.3.1
  
  # AJOUTE TES AUTRES PACKAGES ICI
  # Exemple:
  # provider: ^6.1.2
  # http: ^1.2.2
  # shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  # Si tu as des assets décommente et modifie
  # assets:
  #   - assets/
  #   - assets/images/
