name: Build Flutter App V31 DEBUG - FIX PATH
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
          cache: true
      
      - name: Prepare Project
        run: |
          cd "Find My CNI/find_my_cni_flutter"
          
          flutter clean
          flutter create . --platforms=android  # <-- IMPORTANT: recréer le dossier android
          
          # FIX DEPENDENCIES
          sed -i '/permission_handler/a\  google_fonts: ^6.2.1\n  image_picker: ^1.0.7' pubspec.yaml
          sed -i "s/sdk: '>=3.3.0 <4.0.0'/sdk: '>=3.3.2 <4.0.0'/g" pubspec.yaml
          
          mkdir -p lib/utils
          printf "import 'package:flutter/material.dart';\nOutlinedBorder RoundedCornerShape(double radius) {\n  return RoundedRectangleBorder(borderRadius: BorderRadius.circular(radius));\n}" > lib/utils/widgets.dart
          
          sed -i '1i import "package:find_my_cni/utils/widgets.dart";' lib/screens/declaration_trouve_screen.dart
          sed -i '1i import "package:find_my_cni/utils/widgets.dart";' lib/screens/card_detail_screen.dart
          sed -i '1i import "package:find_my_cni/utils/widgets.dart";' lib/screens/profile_screen.dart
          sed -i '1i import "package:image_picker/image_picker.dart";' lib/screens/declaration_trouve_screen.dart
          find lib -name "*.dart" -exec sed -i 's/GoogleFonts\./TextStyle(fontFamily: "Roboto", /g' {} +
          
      - name: Fix Android Config
        run: |
          cd "Find My CNI/find_my_cni_flutter"
          echo "org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8" >> android/gradle.properties
          echo "org.gradle.networktimeout=300000" >> android/gradle.properties
          echo "android.enableJetifier=true" >> android/gradle.properties
          echo "android.useAndroidX=true" >> android/gradle.properties
          
      - name: Get Packages & Build
        run: |
          cd "Find My CNI/find_my_cni_flutter"
          flutter pub get
          flutter build apk --debug
          
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug-v31
          path: Find\ My\ CNI/find_my_cni_flutter/build/app/outputs/flutter-apk/app-debug.apk
