name: Build Flutter App V20 DEBUG
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "Find My CNI/find_my_cni_flutter"  # <-- DOSSIER DE TON PROJET
    steps:
      - uses: actions/checkout@v4
      
      - name: List files to debug
        run: ls -la  # <-- POUR VOIR SI android/ EXISTE VRAIMENT
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'
      
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --debug  # <-- ON LAISSE FLUTTER GERER GRADLE
      
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug-v20
          path: build/app/outputs/flutter-apk/app-debug.apk
