name: Unzip Project
on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Show files before
        run: ls -la
        
      - name: Download Project.zip
        run: |
          curl -L -o Project.zip "https://github.com/ralover1er-dev/Find_My_CNI-/raw/main/Project.zip"
          ls -la
        
      - name: Unzip
        run: |
          unzip "Project.zip" -d .
          rm "Project.zip"
          ls -la
          
      - name: Commit files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Unzip project" || echo "no changes"
          git push
